# Generated by Django 3.1.5 on 2021-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='song_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
