# Generated by Django 3.1.5 on 2021-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables', '0002_quote_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='quotes',
            field=models.ManyToManyField(blank=True, related_name='_mood_quotes_+', to='quotables.Quote'),
        ),
    ]
