# Generated by Django 4.0.5 on 2022-06-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables', '0004_alter_artist_category_alter_artist_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='quotes',
            field=models.ManyToManyField(blank=True, related_name='+', to='quotables.quote'),
        ),
    ]
