# Generated by Django 4.0.5 on 2022-06-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables', '0006_alter_artist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_image_url',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='category',
            name='quotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='quotables.quote'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='image_url',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
