# Generated by Django 4.0.5 on 2022-06-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables', '0008_alter_artist_profile_image_url_alter_mood_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
